# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import audio_echo_pb2 as audio__echo__pb2


class AudioEchoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.echoAudio = channel.stream_stream(
                '/foo.bar.AudioEcho/echoAudio',
                request_serializer=audio__echo__pb2.Chunk.SerializeToString,
                response_deserializer=audio__echo__pb2.Chunk.FromString,
                )


class AudioEchoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def echoAudio(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioEchoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'echoAudio': grpc.stream_stream_rpc_method_handler(
                    servicer.echoAudio,
                    request_deserializer=audio__echo__pb2.Chunk.FromString,
                    response_serializer=audio__echo__pb2.Chunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'foo.bar.AudioEcho', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AudioEcho(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def echoAudio(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/foo.bar.AudioEcho/echoAudio',
            audio__echo__pb2.Chunk.SerializeToString,
            audio__echo__pb2.Chunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
