audio: &audio_config
  max_wav_value: 32768.0
  sampling_rate: 16000
  n_fft: 1024
  hop_length: 256
  win_length: 1024
  fn_window: 'hanning'
  n_mel_channels: 40
  mel_fmin: 0.0
  mel_fmax: 8000.0
  seed: 1234
  device: 'cpu'
preprocess:
  <<: *audio_config
  sr_model: 16000
  sr_timit: 16000
  sr_noisex: 19980
  symbol_sil_list: ['bcl', 'dcl', 'gcl', 'pcl', 'tcl', 'kcl', 'pau', 'epi', 'h#']
  snr_db_min: -10
  snr_db_max: 12
model:
  <<: *audio_config
  model_name: "DNN"
  train_data: "./preprocessed_dataset/TIMIT/TRAIN"
  test_data: "./preprocessed_dataset/TIMIT/TEST"

  # signal hyper-params
  # neighbor params. {-W, -W+u, -W+2u, …, -1-u, -1, 0, 1, 1+u, …, W-2u, W-u, W}
  # w-1 must be divisible by u
  w: 19
  u: 9

  # model hyper-params
  in_features: 280  # 40-dim mel을 사용하며, neighbor의 갯수가 7개임을 이미 알고 있어서 40*7=280으로 하드코딩
  hidden_features_list: [512, 512, 256, 256]
  dropout: 0.2 # 0이면 없는것과 같음, 1이면 모든 뉴런을 꺼버림
  lr: 0.0001
  batch_size: 1024
  n_epochs: 20
  epochs_per_eval: 1
