// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.15.5
// source: audio-echo.proto

package foo_bar

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Chunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audio_echo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_audio_echo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_audio_echo_proto_rawDescGZIP(), []int{0}
}

func (x *Chunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_audio_echo_proto protoreflect.FileDescriptor

var file_audio_echo_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x2d, 0x65, 0x63, 0x68, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x66, 0x6f, 0x6f, 0x2e, 0x62, 0x61, 0x72, 0x22, 0x1b, 0x0a, 0x05, 0x43,
	0x68, 0x75, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x3c, 0x0a, 0x09, 0x41, 0x75, 0x64, 0x69,
	0x6f, 0x45, 0x63, 0x68, 0x6f, 0x12, 0x2f, 0x0a, 0x09, 0x65, 0x63, 0x68, 0x6f, 0x41, 0x75, 0x64,
	0x69, 0x6f, 0x12, 0x0e, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x62, 0x61, 0x72, 0x2e, 0x43, 0x68, 0x75,
	0x6e, 0x6b, 0x1a, 0x0e, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x62, 0x61, 0x72, 0x2e, 0x43, 0x68, 0x75,
	0x6e, 0x6b, 0x28, 0x01, 0x30, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x66, 0x6f, 0x6f, 0x2e, 0x62, 0x61,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_audio_echo_proto_rawDescOnce sync.Once
	file_audio_echo_proto_rawDescData = file_audio_echo_proto_rawDesc
)

func file_audio_echo_proto_rawDescGZIP() []byte {
	file_audio_echo_proto_rawDescOnce.Do(func() {
		file_audio_echo_proto_rawDescData = protoimpl.X.CompressGZIP(file_audio_echo_proto_rawDescData)
	})
	return file_audio_echo_proto_rawDescData
}

var file_audio_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_audio_echo_proto_goTypes = []interface{}{
	(*Chunk)(nil), // 0: foo.bar.Chunk
}
var file_audio_echo_proto_depIdxs = []int32{
	0, // 0: foo.bar.AudioEcho.echoAudio:input_type -> foo.bar.Chunk
	0, // 1: foo.bar.AudioEcho.echoAudio:output_type -> foo.bar.Chunk
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_audio_echo_proto_init() }
func file_audio_echo_proto_init() {
	if File_audio_echo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_audio_echo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Chunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_audio_echo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audio_echo_proto_goTypes,
		DependencyIndexes: file_audio_echo_proto_depIdxs,
		MessageInfos:      file_audio_echo_proto_msgTypes,
	}.Build()
	File_audio_echo_proto = out.File
	file_audio_echo_proto_rawDesc = nil
	file_audio_echo_proto_goTypes = nil
	file_audio_echo_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AudioEchoClient is the client API for AudioEcho service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AudioEchoClient interface {
	EchoAudio(ctx context.Context, opts ...grpc.CallOption) (AudioEcho_EchoAudioClient, error)
}

type audioEchoClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioEchoClient(cc grpc.ClientConnInterface) AudioEchoClient {
	return &audioEchoClient{cc}
}

func (c *audioEchoClient) EchoAudio(ctx context.Context, opts ...grpc.CallOption) (AudioEcho_EchoAudioClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AudioEcho_serviceDesc.Streams[0], "/foo.bar.AudioEcho/echoAudio", opts...)
	if err != nil {
		return nil, err
	}
	x := &audioEchoEchoAudioClient{stream}
	return x, nil
}

type AudioEcho_EchoAudioClient interface {
	Send(*Chunk) error
	Recv() (*Chunk, error)
	grpc.ClientStream
}

type audioEchoEchoAudioClient struct {
	grpc.ClientStream
}

func (x *audioEchoEchoAudioClient) Send(m *Chunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *audioEchoEchoAudioClient) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AudioEchoServer is the server API for AudioEcho service.
type AudioEchoServer interface {
	EchoAudio(AudioEcho_EchoAudioServer) error
}

// UnimplementedAudioEchoServer can be embedded to have forward compatible implementations.
type UnimplementedAudioEchoServer struct {
}

func (*UnimplementedAudioEchoServer) EchoAudio(AudioEcho_EchoAudioServer) error {
	return status.Errorf(codes.Unimplemented, "method EchoAudio not implemented")
}

func RegisterAudioEchoServer(s *grpc.Server, srv AudioEchoServer) {
	s.RegisterService(&_AudioEcho_serviceDesc, srv)
}

func _AudioEcho_EchoAudio_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AudioEchoServer).EchoAudio(&audioEchoEchoAudioServer{stream})
}

type AudioEcho_EchoAudioServer interface {
	Send(*Chunk) error
	Recv() (*Chunk, error)
	grpc.ServerStream
}

type audioEchoEchoAudioServer struct {
	grpc.ServerStream
}

func (x *audioEchoEchoAudioServer) Send(m *Chunk) error {
	return x.ServerStream.SendMsg(m)
}

func (x *audioEchoEchoAudioServer) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _AudioEcho_serviceDesc = grpc.ServiceDesc{
	ServiceName: "foo.bar.AudioEcho",
	HandlerType: (*AudioEchoServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "echoAudio",
			Handler:       _AudioEcho_EchoAudio_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "audio-echo.proto",
}
